system:
  output_dir:   ./output/simplenagios.cfg
  postcmd:      <optional command to run after config is made>
contacts:
  - id:         admin
    name:       Administrator
    email:      admin@example.com
    prowl:      insert-api-key
groups:
	- id:         administrators
    members:
		  - admin
hosts:
	- name:     webserver.example.com
    ipv4:     127.0.0.1
    group:    administrators
    services:
      - http
  - name:     smtp.example.com
    ip:       127.0.0.1
    group:    administrators
    services:
      - check_ping!400.0,20%!800.0,60%)
      - smtp