# Configuration for status.rb
#
# Path and filename to the nagios status.dat file
dat_file:       /var/spool/nagios/status.dat
#
# Server is optional - if supplied, the script will scp the status.dat file
# from the server on the above location and read it locallly.
# If not supplied it will read the above file locally.
server:         server.example.com
#
# If true, show all hosts and services with status.
# If false, only show non-ok hosts and services
showall:        true
#
# Show a state status summary
status:         true